name: Payfren Release Android
on:
  push:
    tags:
      - '*'
jobs:
  releases:
    name: Build APK
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "18.0"
      FLUTTER_VERSION: "2.10.5"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: $
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: $
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: ncipollo/release-action@v2
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          name: "Payfren Latest Version"
          token: $
